global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "nginx"
    scrape_interval: 1m
    static_configs:
    - targets: ["exporter:9113"]

